### ISSUE TITLE
Add More Documentation

### ISSUE THREAD

**Issue by himanshuk-dev** [himanshuk-dev/Job-Tracker-Automation#3]

**Comment by DeleMike** [comment]
Hi @himanshuk-dev, I'm Michael.

could you clarify more on this issue? I would like to work on it.
What exactly should we be documenting? 
Thanks.

**Comment by himanshuk-dev** [comment]
@DeleMike Thank you for your interest in contributing the documentation.

To start with you could go through the code and demo video on how it works and see if there is any documentation that could be added.
See if you find anything you could work on!

would you like to start with a Step-By-Step guide to work on? This guide must break down the setup instructions into more detailed steps, especially for users who might not be familiar with setting up Google Sheets API credentials or Chrome WebDriver.?

**Comment by DeleMike** [comment]
Hello @himanshuk-dev, many thanks for your response.

I have gone through the code and watched the video. I would prefer to add a step-by-step guide on how it works. 
I will send in a PR for review.

BTW, the documentation file be in what format? a README file? or are we only updating the main README for this issue?

Thanks.
